### ISSUE TITLE
eventric stops after query

### ISSUE THREAD

**Issue by michaelzoidl** [michaelzoidl/entertain.io#29]
## Problem
After calling the *createFeed* via socket.io in the 
**<a href="https://github.com/michaelzoidl/entertain.io/blob/master/src/ui/feed/feed.coffee">src/ui/feed/feed.coffee L15</a>**
```coffeescript
    $scope.doSomething = ->
      socket.emit 'createFeed'
```

the server calls the eventric-command *createFeed*..
Now eventric does some stuff... 

Our subscription to the *Feeds-Projection* starts working:
**<a href="https://github.com/michaelzoidl/entertain.io/blob/master/src/server/server.coffee">src/server/server.coffee L107</a>**
```coffeescript
  feedContext.subscribe "projection:Feeds:changed", (event) ->
    console.log "Feeds Projection Changed"
    feedContext.query "getAllFeeds"
    .then (feeds) ->
      console.log feeds
      io.emit 'mongoFeeds', feeds
    return
```

But the `console.log feeds` never starts, @johannesbecker do you see the failure in the code?
(*fyi The mongodb is running and works fine.*)

## Eventric Query Handler
**<a href="https://github.com/michaelzoidl/entertain.io/blob/master/src/context/feed/index.coffee">src/context/feed/index.coffee L45</a>**
```coffeescript
feedContext.addQueryHandler "getAllFeeds", (params, callback) ->
  @$projectionStore("mongodb", "Feeds").then (feedsMongoDbCollection) ->
    feedsMongoDbCollection.find {}, (feedsCursor) ->
      feedsCursor.toArray (feedsArray) ->
        callback null, feedsArray
        return
      return
    return
  return
```

**Comment by johannesbecker** [comment]
The feed context seems outdated, this was the latest version: https://gist.github.com/johannesbecker/53b6fa6ce9aab13c3476
